### ISSUE TITLE
Incredible lags

### ISSUE THREAD

**Issue by codenyte** [itsmartashub/floristyle#2]
I really want to use this Fork of FlorisBoard and I like it so far, but it's pretty much unusable. Whether I'm in the keyboard settings or using the keyboard itself, I get incredible lags when using the app. I use a Google Pixel 6a running GrapheneOS (Android 14).

**Comment by itsmartashub** [comment]
Hey, I'm really sorry to hear that. It's very possible that it's because Florisboard hasn't been updated for a long time and I guess it isn't set for A14 yet.

I must clarify that this is not an Florisboard fork. These are just dynamic themes (`flex` file) which works only with the `apk` attached here or you can build your own directly from the [source](https://github.com/1fexd/florisboard).
This `apk` version here is from Florisboard's GitHub actions (put here only for easier discovery and quick download) before it expired and is managed by Florisboard contributor [1fexd](https://github.com/1fexd/).
Please make sure to read the readme file thoroughly. I'm sorry if it's confusing.

Anyway, Patrick (Florisboard maintainer) recently mentioned that [he's coming back](https://github.com/florisboard/florisboard/discussions/2197) with [new updates](https://github.com/florisboard/florisboard/discussions/2314) for Florisboard soon. He should also merge the 1fexd's material you feature, so you should likely be able to use future keyboard updates with those themes here.

PS If you read the readme here, can you tell me what made you think this is a fork? Is it the repo name, or maybe the 'apk' file attached in releases? That would be helpful.

**Comment by itsmartashub** [comment]
@codenyte Hm, I'm not sure what bugs you're referring to? Is it the keyboard itself, some of its functionality, or issues related to themes?

Like @TeaOwO said, this is indeed a `debug apk` version, and instabilities, bugs, and crashes are possible, and we can't control that.

Thank you for letting me know why you thought this was a fork, and I can totally understand why you didn't read the entire readme. It's long, but I simply wanted to cover everything. Also, when someone sees an `apk` in the releases, they might automatically think it's a fork. I appreciate your honesty.

**Comment by itsmartashub** [comment]
Yes, the debug version was there for us impatient ones who love Florisboard but also likes the Material You and Gboard UI. Now, in the official version, many things have been fixed, and I'm glad that everything is working well for you too 🫠
